import type { Metadata } from "next";
import Link from "next/link";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "18 U.S.C. § 2257 Compliance — VeilWick",
  description:
    "2257 record-keeping compliance statement for VeilWick. Synthetic fictional adults 18+ only. Custodian of records: VeilWick LLC.",
  robots: { index: true, follow: true },
};

export default function Legal2257Page() {
  const year = new Date().getFullYear();
  return (
    <div className="min-h-dvh bg-zinc-950 text-zinc-100">
      <div className="mx-auto max-w-3xl px-6 py-12">
        <Link
          href="/"
          className="text-sm text-zinc-400 hover:text-white underline underline-offset-4"
        >
          ← Back to VeilWick
        </Link>

        <h1 className="mt-6 text-3xl font-bold tracking-tight">
          18 U.S.C. § 2257 Compliance Statement
        </h1>
        <p className="mt-2 text-sm text-zinc-400">
          Record-Keeping Requirements for Producers of Visual Depictions — VeilWick
        </p>

        <div className="mt-8 rounded-xl border border-white/10 bg-zinc-900 p-6">
          <h2 className="text-sm font-semibold tracking-wide text-white">
            Custodian of Records
          </h2>
          <address className="mt-3 not-italic text-sm leading-relaxed text-zinc-300">
            <span className="font-semibold text-white">VeilWick LLC</span>
            <br />
            Custodian of Records — 18 U.S.C. § 2257
            <br />
            548 Market Street, Suite 40012
            <br />
            San Francisco, CA 94104
            <br />
            United States
            <br />
            <span className="mt-2 inline-block">
              Email:{" "}
              <a
                href="mailto:legal@veilwick.com"
                className="underline underline-offset-4 hover:text-white"
              >
                legal@veilwick.com
              </a>
            </span>
          </address>
        </div>

        <div className="mt-8 space-y-6 text-sm leading-7 text-zinc-300">
          <section>
            <h2 className="text-base font-semibold text-white">
              1. Compliance Statement
            </h2>
            <p className="mt-2">
              In compliance with 18 U.S.C. § 2257 and 28 C.F.R. Part 75, VeilWick LLC,
              as the producer of visual depictions that contain explicit sexual conduct
              as defined in 18 U.S.C. § 2256, maintains all records required by law
              with respect to performers depicted in such content, including records
              containing the names and dates of birth of performers and copies of
              identification documents as required.
            </p>
            <p className="mt-3">
              All records required to be maintained pursuant to 18 U.S.C. § 2257 are
              maintained by the Custodian of Records at the address listed above and
              are available for inspection as required by law.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white">
              2. Synthetic / AI-Generated Content Disclaimer
            </h2>
            <p className="mt-2">
              VeilWick is an <strong className="text-white">NSFW-only, synthetic, fictional</strong>{" "}
              platform. The majority of visual depictions on VeilWick are generated by
              artificial intelligence (including Wan 2.4-14B and H3 synthesis) and do not
              depict real persons, living or deceased. All synthetic characters are
              intentionally generated and presented as consenting fictional adults who are
              18 years of age or older. No real persons are depicted in synthetic content.
            </p>
            <p className="mt-3">
              Where synthetic content is displayed, it is labeled as AI-generated / synthetic
              and is not subject to 2257 record-keeping as it does not depict an actual
              human being. This service is strictly 18+ and is not intended for minors.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white">
              3. Age Requirement — 18+ Only
            </h2>
            <p className="mt-2">
              VeilWick is for adults only. You must be at least 18 years of age (or the
              age of majority in your jurisdiction, whichever is greater) to access the
              feed, series, live rooms, or any API that delivers explicit content. Access
              is gated by an age-verification check that sets the httpOnly cookie{" "}
              <code className="rounded bg-white/10 px-1 py-0.5 text-xs text-white">
                veilwick_age_verified
              </code>{" "}
              after you confirm you are 18+ (stored 1 year, SameSite=Lax). If you are
              not 18+, you must leave the site via the &quot;Exit to safety&quot; control.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white">
              4. Third-Party / User-Submitted Content
            </h2>
            <p className="mt-2">
              To the extent VeilWick displays content produced by third parties, VeilWick
              relies on the representations and 2257 compliance of the original producer.
              VeilWick prohibits uploads that depict minors, non-consensual conduct, or
              real persons without verified 18+ records. Any content found in violation
              is removed promptly upon notice.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white">5. No SFW Version</h2>
            <p className="mt-2">
              VeilWick is NSFW-only. There is no separate SFW version of the feed, series,
              or live experience. The public landing page and this legal notice are the
              only store-safe, SFW surfaces suitable for PWA install and store listing;
              all explicit surfaces (/feed, /series, /series/[id], /live/*, /api/feed,
              /api/series) are gated behind the 18+ verification and are marked noindex.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white">
              6. Contact &amp; Takedown
            </h2>
            <p className="mt-2">
              If you believe content on VeilWick violates 2257, depicts a real minor, or
              misrepresents synthetic content as real, contact the Custodian of Records
              at{" "}
              <a
                href="mailto:legal@veilwick.com"
                className="underline underline-offset-4 hover:text-white"
              >
                legal@veilwick.com
              </a>{" "}
              with a description of the material and URL. We will investigate and remove
              or correct the material as required by law.
            </p>
          </section>

          <section className="rounded-lg border border-amber-500/20 bg-amber-500/10 p-4 text-amber-100">
            <h2 className="text-sm font-semibold">Fictional Demo Notice</h2>
            <p className="mt-1 text-sm leading-6 text-amber-100/90">
              VeilWick in this deployment is a fictional demo environment. Any resemblance
              to real persons is coincidental and unintended. All explicit depictions are
              either of consenting adults 18+ with records on file with the Custodian, or
              are entirely synthetic/AI-generated fictional adults 18+. No real persons are
              depicted in synthetic scenes.
            </p>
          </section>

          <p className="pt-4 text-xs text-zinc-500">
            Last updated: {year} — VeilWick LLC. This statement is provided for compliance
            with 18 U.S.C. § 2257 and does not constitute legal advice.
          </p>
        </div>

        <div className="mt-10 flex flex-wrap gap-3">
          <Link
            href="/"
            className="inline-flex rounded-full bg-white px-6 py-2 text-sm font-bold text-black hover:bg-zinc-100"
          >
            Back to Home
          </Link>
          <Link
            href="/feed"
            className="inline-flex rounded-full border border-white/15 px-6 py-2 text-sm font-semibold text-white hover:bg-white/10"
          >
            Enter Feed (18+)
          </Link>
        </div>
      </div>
    </div>
  );
}
