import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, basename } from "node:path";

interface ManifestEntry {
  name: string;
  layer: "primitives" | "composites" | "data-display" | "layout";
  importPath: string;
  file: string;
  exports: string[];
}

interface RootSpec {
  layer: ManifestEntry["layer"];
  dir: string;
  importPrefix: string;
}

const ROOTS: RootSpec[] = [
  { layer: "primitives", dir: "packages/ui/src/primitives", importPrefix: "@repo/ui/primitives/" },
  { layer: "composites", dir: "packages/ui/src/composites", importPrefix: "@repo/ui/composites/" },
  {
    layer: "data-display",
    dir: "apps/web/src/components/ui/data-display",
    importPrefix: "@/components/ui/data-display/",
  },
  {
    layer: "layout",
    dir: "apps/web/src/components/ui/layout",
    importPrefix: "@/components/ui/layout/",
  },
];

const EXPORT_RE =
  /export\s+(?:async\s+)?(?:const|function|class|type|interface|enum)\s+([A-Za-z_$][\w$]*)/g;
const EXPORT_DECLARATION_LIST_RE = /export\s+\{\s*([^}]+)\s*\}/g;

function extractExports(src: string): string[] {
  const exports = new Set<string>();
  let m: RegExpExecArray | null;
  EXPORT_RE.lastIndex = 0;
  while ((m = EXPORT_RE.exec(src)) !== null) {
    exports.add(m[1]);
  }
  EXPORT_DECLARATION_LIST_RE.lastIndex = 0;
  while ((m = EXPORT_DECLARATION_LIST_RE.exec(src)) !== null) {
    for (const part of m[1].split(",")) {
      const name = part.trim().split(/\s+as\s+/i).pop()?.trim();
      if (name && /^[A-Za-z_$][\w$]*$/.test(name)) exports.add(name);
    }
  }
  return [...exports];
}

function pascalFromKebab(s: string): string {
  return s.replace(/(^|-)([a-z])/g, (_, __, c) => c.toUpperCase());
}

function pickPrimaryExport(exports: string[], file: string): string {
  const stem = basename(file).replace(/\.tsx?$/, "");
  const expected = pascalFromKebab(stem);
  if (exports.includes(expected)) return expected;
  return exports.find((e) => /^[A-Z]/.test(e)) ?? exports[0] ?? expected;
}

async function dirExists(p: string): Promise<boolean> {
  try {
    const s = await stat(p);
    return s.isDirectory();
  } catch {
    return false;
  }
}

export async function buildManifest(opts: { workDir?: string } = {}): Promise<void> {
  const work = opts.workDir ?? process.cwd();
  const out: ManifestEntry[] = [];

  for (const root of ROOTS) {
    const abs = join(work, root.dir);
    if (!(await dirExists(abs))) continue;
    const entries = await readdir(abs);
    for (const f of entries) {
      if (!f.endsWith(".tsx") && !f.endsWith(".ts")) continue;
      if (f === "index.ts" || f === "index.tsx") continue;
      const filePath = join(abs, f);
      const src = await readFile(filePath, "utf8");
      const exports = extractExports(src);
      if (exports.length === 0) continue;
      const stem = f.replace(/\.tsx?$/, "");
      out.push({
        name: pickPrimaryExport(exports, f),
        layer: root.layer,
        importPath: `${root.importPrefix}${stem}`,
        file: join(root.dir, f),
        exports: exports.sort(),
      });
    }
  }

  out.sort((a, b) => a.importPath.localeCompare(b.importPath));

  const manifest = {
    description:
      "Generated by scripts/build-manifest.ts. Do not edit by hand. Run `bun run manifest` to regenerate.",
    components: out,
  };

  await writeFile(
    join(work, "MANIFEST.json"),
    JSON.stringify(manifest, null, 2) + "\n",
    "utf8",
  );
}

const isMain = (() => {
  try {
    if (typeof process === "undefined" || !process.argv[1]) return false;
    return import.meta.url === `file://${process.argv[1]}`;
  } catch {
    return false;
  }
})();

if (isMain) {
  buildManifest().then(
    () => console.log("MANIFEST.json updated."),
    (err: Error) => {
      console.error(err);
      process.exit(1);
    },
  );
}
